// Code generated by "enumer -type=Environment -json -text -yaml -sql -transform=snake"; DO NOT EDIT.

package config

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _EnvironmentName = "productiondeveloplocal"

var _EnvironmentIndex = [...]uint8{0, 10, 17, 22}

const _EnvironmentLowerName = "productiondeveloplocal"

func (i Environment) String() string {
	if i < 0 || i >= Environment(len(_EnvironmentIndex)-1) {
		return fmt.Sprintf("Environment(%d)", i)
	}
	return _EnvironmentName[_EnvironmentIndex[i]:_EnvironmentIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EnvironmentNoOp() {
	var x [1]struct{}
	_ = x[Production-(0)]
	_ = x[Develop-(1)]
	_ = x[Local-(2)]
}

var _EnvironmentValues = []Environment{Production, Develop, Local}

var _EnvironmentNameToValueMap = map[string]Environment{
	_EnvironmentName[0:10]:       Production,
	_EnvironmentLowerName[0:10]:  Production,
	_EnvironmentName[10:17]:      Develop,
	_EnvironmentLowerName[10:17]: Develop,
	_EnvironmentName[17:22]:      Local,
	_EnvironmentLowerName[17:22]: Local,
}

var _EnvironmentNames = []string{
	_EnvironmentName[0:10],
	_EnvironmentName[10:17],
	_EnvironmentName[17:22],
}

// EnvironmentString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EnvironmentString(s string) (Environment, error) {
	if val, ok := _EnvironmentNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EnvironmentNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Environment values", s)
}

// EnvironmentValues returns all values of the enum
func EnvironmentValues() []Environment {
	return _EnvironmentValues
}

// EnvironmentStrings returns a slice of all String values of the enum
func EnvironmentStrings() []string {
	strs := make([]string, len(_EnvironmentNames))
	copy(strs, _EnvironmentNames)
	return strs
}

// IsAEnvironment returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Environment) IsAEnvironment() bool {
	for _, v := range _EnvironmentValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Environment
func (i Environment) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Environment
func (i *Environment) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Environment should be a string, got %s", data)
	}

	var err error
	*i, err = EnvironmentString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Environment
func (i Environment) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Environment
func (i *Environment) UnmarshalText(text []byte) error {
	var err error
	*i, err = EnvironmentString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for Environment
func (i Environment) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Environment
func (i *Environment) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = EnvironmentString(s)
	return err
}

func (i Environment) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Environment) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Environment: %[1]T(%[1]v)", value)
	}

	val, err := EnvironmentString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
